controllers:
    resource: ../src/Controller/
    type: attribute
# the "home" route name is not important yet
home:
    path: /
    controller: App\Controller\Home::home
help:
    path: /help
    controller: App\Controller\Help::help
api_login_check:
    path: /api/login_check