controllers:
    resource: ../src/Controller/
    type: attribute
# the "home" route name is not important yet
home:
    path: /
    controller: App\Controller\Home::home
help:
    path: /help
    controller: App\Controller\Help::help
info:
    path: /info
    controller: App\Controller\Help::info

mentionlegal:
    path: /mention-legale
    controller: App\Controller\Help::mentionlegal

motdepasseoublie:
    path: /mot-de-passe-oublie
    controller: App\Controller\Help::motdepasseoublie
    
cgu:
    path: /cgu
    controller: App\Controller\Help::cgu


api_login_check:
    path: /api/login_check

dashboard:
    path: /admin
    controller: App\Controller\Admin\DashboardController::index